version: '3.8'

volumes:
  stage_traefik: {}
  stage_django_media:
    external: true
    name: mynorm_production_django_media
  stage_redis_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/shared/django/Dockerfile

    image: mynorm_stage_django
    volumes:
      - stage_django_media:/app/media
    depends_on:
      - redis
    env_file:
      - .env.stage
    command: /start
    ports:
      - '5000:5000'

  redis:
    image: redis:7-alpine
    volumes:
      - stage_redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'

  traefik:
    build:
      context: .
      dockerfile: ./compose/shared/traefik/Dockerfile
    image: mynorm_stage_traefik
    depends_on:
      - django
      - nginx
    volumes:
      - ./compose/stage/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - stage_traefik:/etc/traefik/acme
    ports:
      - '80:80'
      - '443:443'

  nginx:
    build:
      context: .
      dockerfile: ./compose/shared/nginx/Dockerfile
    image: mynorm_stage_nginx
    depends_on:
      - django
    volumes:
      - stage_django_media:/usr/share/nginx/media:ro
    ports:
      - '8080:8080'

  front:
    build:
      context: ../mera/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

